### ISSUE TITLE
Simple User Password Grabber doesn't work

### ISSUE THREAD

**Issue by Mr-Savag3** [hak5/usbrubberducky-payloads#113]
There's hardly any documentation for this payload, so I'm not sure I'm doing anything right. I filled in all the blanks, but I still get several errors throughout the process. I added a direct download link to get mimikatz, I put email and passwords in, and I get errors immediately after the mimikatz download, "System could not find the file specified", and then another as it's trying to send the email. They're not on screen long enough to read, but the errors are best summarized as "The SMTP server requires a secure server and the client was not authenticated" or something like that.

**Comment by 0iphor13** [comment]
Well I think opening an issue is wrong in this case. Payloads are community made, so your best best is to contact the creator. 

When it comes to mimikatz, I am sure it simply gets killed and deleted by AV, because, it's mimikatz, lol x) And the other error maybe gets caused by this, as the payload is not executed properly, but that's just a guess. 

always keep in mind, these payloads were made by the community and some are quiet old and weren't updated and are considered to be dead.

But within the Hak5 discord there are a lot of people willing to help with payload creation and modification, maybe you can try out this path. I hope I was able to provide a lil bit of help to you.

**Comment by Mr-Savag3** [comment]
Oh, sorry I'm new to GitHub I didn't know how this works, I thought the issue tab was for like if you're having trouble getting it to work, I apologize. I'll look deeper into it and maybe contact the dev, thanks!
