### ISSUE TITLE
Payload not functioning 

### ISSUE THREAD

**Issue by G4k3r** [hak5/usbrubberducky-payloads#293]
### Payload Title

Windows Privilege Excalibur 

### Payload URL

https://github.com/hak5/usbrubberducky-payloads/windows_privilege_Excalibur 

### Description

I followed entire instructions to setup the load and when i inserted the ducky into the test machine it ran the script but nothing happened a cmd shell was spawned and closed no information went into my dropbox account?

### Checklist ✅

- [X] I checked and didn't find a similar issue already reported
- [X] I am using PayloadStudio to encode this payload
- [X] I made sure to redact any private information in the details shared above
- [X] I have read the documentation provided by the original payload author and configured the payload (if required)
- [X] I have confirmed I am deploying this payload with the correct device intended by the original author (Original USB Rubber Ducky vs New USB Rubber Ducky)
- [X] I have confirmed I am deploying this payload on the correct target host intended by the original author (Windows, Mac, Linux, etc)
- [X] I have confirmed the payload is compiled in the correct keyboard language for the target host I'm trying to deploy it on (US, DE, etc)
- [X] I have actually read the above checkboxes before checking them, including this one, which I have intentionally left unchecked as confirmation of this statement

**Comment by dallaswinger** [comment]
❌ URL provided is not valid - its a 404. 

❌  The last checkbox says
_"I have actually read the above checkboxes before checking them, including this one, which I have intentionally left unchecked as confirmation of this statement"_
yet, you checked it?

The payload (which I was only able to find because you at least provided the title) appears it requires **several** things to be configured. One of those things, for example, is the address of the server you are hosting the staged script itself on:
`REM Replace REMOTE_IP_ADDRESS with the actual IP address of the remote server hosting the script.`

❌  You have not confirmed you've completed this (or any of the other steps required by the payload) by leaving most of the sections of this form including `Payload Modifications` entirely blank. **I suspect this is one of potentially many problems you're facing.** 

Filling out this form with relevant details will go a long ways; people cannot read your mind unfortunately.

Start by confirming the actual steps you've taken to configure and deploy the payload. This is why the issue creation form asks you for such information.

**Comment by G4k3r** [comment]
okay thank you
